[package]
name = "cetana"
version = "0.1.0"
edition = "2021"

[features]
default = ["cpu"]
cpu = []
cuda = []
vulkan = ["dep:ash"]
mps = []

[dependencies]
ash = { version = "0.38.0", optional = true, features = ["linked"] }


[dev-dependencies]
csv = "1.3"
rand = "0.8.5"
pinax = "0.1.0"
